n = int(input('Введите первое число n: '))
m = int(input('Введите второе число m: '))
print(f'Сумма: {n + m}')
print(f'Разность: {n - m}')
print(f'Произведение: {n * m}')
print(f'Деление: {n / m}' if m != 0 else 'Деление на 0')
print(f'Возвести n в степень m: {n ** m}')